spring.application.name=fx-currency-backend
spring.docker.compose.enabled=false
external.fixer.api-key=05a67d44085840dd3572874e4e67d388
external.fixer.base-url=https://data.fixer.io/api
resttemplate.max-total-connections=100
resttemplate.max-per-route=20
resttemplate.connect-timeout=5000
resttemplate.read-timeout=5000
resttemplate.connection-request-timeout=2000
resttemplate.idle-connection-evict-seconds=30
exchange.job.currency-pairs[0]=USD,TRY
exchange.job.currency-pairs[1]=EUR,USD
exchange.job.currency-pairs[2]=GBP,TRY
exchange.job.cron=0 */3 * * * *
redis.host=localhost
redis.port=6379
redis.connectionPoolSize=64
redis.connectionMinimumIdleSize=10
redis.timeout=3000
redis.retryCount=3
redis.retryInterval=1000
cache.exchange-rate.ttl=600000
cache.exchange-rate.idle=300000